FROM golang:1.25-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/user-service ./services/user-service

FROM gcr.io/distroless/static-debian12:nonroot

USER 1000:1000

COPY --from=builder /build/user-service /app/user-service

EXPOSE 50051

ENTRYPOINT ["/app/user-service"]
