apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-services-config
  labels:
    {{- include "grpc-services.labels" (dict "name" "grpc-services" "version" "v1") | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.global.logLevel }}
  OTLP_ENDPOINT: {{ .Values.global.otlpEndpoint }}
