apiVersion: v1
kind: Secret
metadata:
  name: grpc-client-tls
  namespace: grpc-services
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQW5xZ0F3SUJBZ0lVT29TQ21rME5wVUlkaTZid0F4RjlKS1J4SFZzd0NnWUlLb1pJemowRUF3SXcKZ1o4eEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIRXcxVApZVzRnUm5KaGJtTnBjMk52TVI4d0hRWURWUVFLRXhablVsQkRJRTFwWTNKdmMyVnlkbWxqWlhNZ1VHOURNUjR3CkhBWURWUVFMRXhWRFpYSjBhV1pwWTJGMFpTQkJkWFJvYjNKcGRIa3hJakFnQmdOVkJBTVRHV2RTVUVNZ1RXbGoKY205elpYSjJhV05sY3lCRVpYWWdRMEV3SGhjTk1qWXdOVEV5TVRVek56QXdXaGNOTWpjd05URXlNVFV6TnpBdwpXakNCaHpFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNUCkRWTmhiaUJHY21GdVkybHpZMjh4SHpBZEJnTlZCQW9URm1kU1VFTWdUV2xqY205elpYSjJhV05sY3lCUWIwTXgKRkRBU0JnTlZCQXNUQzJGd2FTMW5ZWFJsZDJGNU1SUXdFZ1lEVlFRREV3dGhjR2t0WjJGMFpYZGhlVEJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkdVd0VZZWhxaHRib245MTh5ZHhISlA5ajFnNEVQTVhXSjUxCjdmUWxWZFdtWTBmWjZ0ZzRFYjVPSkJlNXZpR1Vra2NHeFNlY1lQbCtqNXZtM3pUVGJxQ2pnYWt3Z2FZd0RnWUQKVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVgpIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFPcVpYRDBLSmlmaHpyMm1RWlBhekJTVTBDV0RBZkJnTlZIU01FCkdEQVdnQlJQdm9VTjBCVlMwMVorZlI1TFRBUWx6bmw0NVRBbkJnTlZIUkVFSURBZWdnbHNiMk5oYkdodmMzU0MKQzJGd2FTMW5ZWFJsZDJGNWh3Ui9BQUFCTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSURiWmhHUFZjT0hxenhTeQpHUkxVc1dlanBFWWJjMkNsTnRqY0JJUEszYXV3QWlBSk14RVpKZlhUalhRUGpWQlJ6Vk5lL3dWL2kvL2xCWUg3Cm5BYlNxa1BJSGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUczV3JRSTF0b2xOemYyYmp1cXE1YmtlQytXelRlS0JaUDJFWmhMRFZUNWpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWlRBUmg2R3FHMXVpZjNYekozRWNrLzJQV0RnUTh4ZFlublh0OUNWVjFhWmpSOW5xMkRnUgp2azRrRjdtK0laU1NSd2JGSjV4ZytYNlBtK2JmTk5OdW9BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: grpc-ca
  namespace: grpc-services
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNoRENDQWlxZ0F3SUJBZ0lVZU5id05DMXIrdzRCYUIyejZOV1lVNGZCOWxzd0NnWUlLb1pJemowRUF3SXcKZ1o4eEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIRXcxVApZVzRnUm5KaGJtTnBjMk52TVI4d0hRWURWUVFLRXhablVsQkRJRTFwWTNKdmMyVnlkbWxqWlhNZ1VHOURNUjR3CkhBWURWUVFMRXhWRFpYSjBhV1pwWTJGMFpTQkJkWFJvYjNKcGRIa3hJakFnQmdOVkJBTVRHV2RTVUVNZ1RXbGoKY205elpYSjJhV05sY3lCRVpYWWdRMEV3SGhjTk1qWXdOVEV5TVRVek56QXdXaGNOTXpZd05UQTVNVFV6TnpBdwpXakNCbnpFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNUCkRWTmhiaUJHY21GdVkybHpZMjh4SHpBZEJnTlZCQW9URm1kU1VFTWdUV2xqY205elpYSjJhV05sY3lCUWIwTXgKSGpBY0JnTlZCQXNURlVObGNuUnBabWxqWVhSbElFRjFkR2h2Y21sMGVURWlNQ0FHQTFVRUF4TVpaMUpRUXlCTgphV055YjNObGNuWnBZMlZ6SUVSbGRpQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRzJhCnY5aEEvSUdXbk9iZ2ZxN0U1b0dZdGlWeTZ3NFNlVlFRdHhxcjE5U01nZGQxZzl4aDNiZ1FDaXo4VUJYdXBFZGoKeXdUNTQwZnJGSUZHNWc4SWpFYWpRakJBTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUIwR0ExVWREZ1FXQkJSUHZvVU4wQlZTMDFaK2ZSNUxUQVFsem5sNDVUQUtCZ2dxaGtqT1BRUURBZ05JCkFEQkZBaUIrSlRYRXQrTFJrQjVRNmVjVVJwVWtqckF6cUtub0F6QVFXdXFNSmdSN05RSWhBS21qUFBvN2FrS3gKblVITFJaREpyakdpbUJxL1pKNFlCRm1UMHhJVWVwNEsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: grpc-services
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "grpc-services/grpc-client-tls"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /user.v1.UserService
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 50051
      - path: /order.v1.OrderService
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 50052
