global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:9091"]
        labels:
          service: "user-service"

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:9092"]
        labels:
          service: "order-service"

  - job_name: "envoy"
    metrics_path: "/stats/prometheus"
    static_configs:
      - targets: ["envoy:9901"]
        labels:
          service: "envoy"

  - job_name: "cert-exporter"
    static_configs:
      - targets: ["cert-exporter:9810"]
        labels:
          service: "cert-exporter"
